### ISSUE TITLE
Deprecated use of validate_qobj_against_schema

### ISSUE THREAD

**Issue by exAClior** [qiskit-community/qiskit-quantinuum-provider#19]
### Information

- **Qiskit Honeywell Provider version**: Latest Version from github
- **Python version**: 3.9
- **Qiskit Terra version**: 0.19.1
- **Operating system**: Arch Linux 5.15.13

### What is the current behavior?

Executing 
`from qiskit.providers.honeywell import Honeywell` 
gives `ImportError: cannot import name 'validate_qobj_against_schema' from 'qiskit.qobj'`

### Steps to reproduce the problem

Do the import mentioned above with Qiskit Terra version 0.19.1. 

### What is the expected behavior?

Should import correctly

### Suggested solutions

In this upgrade log, https://github.com/Qiskit/qiskit-terra/blob/d5094eeca27f2c0f3c13f23f1e812cd41b6108f2/releasenotes/notes/0.19/remove-schemas-ca9f3f2e0f08bca8.yaml , it suggests to manually building jsonschema
 validation function. From a new user's perspective, it is not clear what to do exactly.

**Comment by dlucchetti** [comment]
Thank you for posting the issue.  The near term solution is likely to comment out the two lines that reference validate_qobj_against_schema from honeywelljob.py.

We will start working on a real solution.

**Comment by mtreinish** [comment]
This should have been fixed by #14 (which I let sit idle for too long). @exAClior if you can test that things work from the master branch I can prepare to get a release out with that PR (and other fixes on master).

**Comment by exAClior** [comment]
@mtreinish  Thank you for the fix! I ran my code using the master branch version. It seems to be working. I could submit jobs.

**Comment by exAClior** [comment]
It seems that the related code change has been merged. I will close this issue for now.
