### ISSUE TITLE
package not working? 

### ISSUE THREAD

**Issue by petergthatsme** [qiskit-community/qiskit-quantinuum-provider#32]
### Information

I was wondering what the status of this package is? Is it meant to be currently operational? 
Are there plans to have it in pypi? 

- **Qiskit Quantinuum Provider version**: master
- **Python version**:  3.9.13
- **Operating system**: ubuntu 22.04

### What is the current behavior?

Currently installing `qiskit-quantinuum-provider` via source (as shown in https://github.com/qiskit-community/qiskit-quantinuum-provider/issues/27 ) seems to not work for me. 

It seems that the package tries to establish/verify credentials on import. For example running `from qiskit_quantinuum import Quantinuum` from a command-line interpreter just gets stuck.
Running that from within a jupyter notebook brings out my browser's keyring dialog, which I can't seem to get through.

Assuming this package is actually meant to be operational(?), it could make sense to separate importing from any sort of account management. Since I can't import the package, I can't delete/load/save any account info. 

### Steps to reproduce the problem

run `from qiskit_quantinuum import Quantinuum` from a command-line interpreter. 

### What is the expected behavior?

import succeeds and one can run commands to manage account (i.e. login, delete, save)

### Suggested solutions

would be good to have it clearly stated if this package is actually meant to be used. 
Thanks!

**Comment by chris-theroux** [comment]
Hey Peter,

We are still supporting this package.
I'll start looking into the import issues.

We do want the package on pypi but we need help from the Qiskit team (@mtreinish).

**Comment by chris-theroux** [comment]
Hey Peter,

I apologize for the late update but the package should be available on pypi.
Please re-open this issue if you cannot access it.

Thanks!
